version: '3.9'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: ai-content-assistant-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aiuser
      POSTGRES_PASSWORD: aipassword
      POSTGRES_DB: aicontentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: